name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Manifest plugin version
        required: true

  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: make build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            trivy-aws-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set new version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "NEW_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set new version from input
        if: github.event_name == 'workflow_dispatch'
        run: echo "NEW_VERSION=${{github.event.inputs.version}}" >> $GITHUB_ENV

      - name: Bump manifest
        run: make bump-manifest

      - name: Push changes
        run: |
            git config --global user.name 'GitHub Actions' ;\
            git config --global user.email 'actions@github.com' ;\
            git add plugin.yaml ;\
            git commit -m "chore: bump manifest to $NEW_VERSION"
            git pull origin main --rebase
            git push origin main
